version: '2.1'

services:
  thesis_before_mid:
    image: thesis_before_mid
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 index.js